import os
import pandas as pd
import random

def AMPGAN_v3(input_data: dict) -> str:
    min_length = input_data.get("min_length", 10)
    max_length = input_data.get("max_length", 100)
    num_generations = input_data.get("num_generations", 1)
    folder_path = input_data.get("folder_path", None)

    # AA list
    AA_LIST = [
        "A", "R", "N", "D", "C",
        "Q", "E", "G", "H", "I",
        "L", "K", "M", "F", "P",
        "S", "T", "W", "Y", "V"
    ]
    sequences = []
    for _ in range(num_generations):
        length = random.randint(min_length, max_length)
        sequence = "".join(random.choices(AA_LIST, k=length))
        sequences.append(sequence)
    csv_path = os.path.join(folder_path, "generated_sequences.csv")
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        num_original = len(df)
        
        # append new sequences to existing ones;
        # df might include the other columns generated by filters
        # so we leave those columns unchanged and only append new sequences with empty values for the filter columns
        new_df = pd.DataFrame({"sequence": sequences})
        for col in df.columns:
            if col != "sequence":
                new_df[col] = "new"
        df = pd.concat([df, new_df], ignore_index=True)
        df.to_csv(os.path.join(folder_path, "generated_sequences.csv"), index=False)
        return (
            f"Successfully generated {len(sequences)} new sequences using AMPGAN-v3 "
            f"(min_length={input_data['min_length']}, max_length={input_data['max_length']}). "
            f"Appended to existing file: {csv_path}. "
            f"(Previous total: {num_original} | New total: {len(df)}). "
            f"Missing filter columns for the new entries were safely filled with NA.\n"
        )
    else:
        df = pd.DataFrame({"sequence": sequences})
        df.to_csv(os.path.join(folder_path, "generated_sequences.csv"), index=False)

        return f"Generated {len(sequences)} sequences using AMPGAN-v3 with parameters: min_length={input_data['min_length']}, max_length={input_data['max_length']}, num_generations={input_data['num_generations']}. The result is saved in {csv_path}\n"

    
